### ISSUE TITLE
Certain broken apps

### ISSUE THREAD

**Issue by duraidabdul** [andrewwiik/LittleX#16]
Not sure if this is possible, but it would be great to have an option to disable LittleX in certain apps which don't function properly with the tweak installed, an example being Clash of Clans, and the music app.

**Comment by andrewwiik** [comment]
I want to add this feature and once I know how to do preferences in Electra I will try, also music app works fine on my device

**Comment by KikeMartinG** [comment]
Music app works just fine

**Comment by duraidabdul** [comment]
To set up preferences with Electra, it’s just like normal. Preference plist and bundles are in /bootstrap/Library

**Comment by duraidabdul** [comment]
Also, it doesn't completely break music, only problem is that the media controls get compressed, making the volume and seeking controls to vertically close to each other
