### ISSUE TITLE
Fix Instagram transparent bar header

### ISSUE THREAD

**Issue by KikeMartinG** [andrewwiik/LittleX#18]
![3ef11417-9790-4f8b-a862-7293882ccf52](https://user-images.githubusercontent.com/15319495/35694794-14ebdd84-0748-11e8-929a-951bf0e8407e.jpeg)

**Comment by 503es** [comment]
![890f53a7-36d4-4d27-91cb-24e6a8a822df](https://user-images.githubusercontent.com/36049586/35695564-b9559964-0739-11e8-936c-c8fd113660a0.png)

**Comment by andrewwiik** [comment]
Fixed in latest beta
