### ISSUE TITLE
Fix MyVidster overlapping

### ISSUE THREAD

**Issue by KikeMartinG** [andrewwiik/LittleX#20]
![08f1220d-7c51-4fed-a98e-aeaf4b48f332](https://user-images.githubusercontent.com/15319495/35695027-e0900d8e-0748-11e8-8b93-8123db7fb554.png)

**Comment by andrewwiik** [comment]
What's the icon for the app, because the one I downloaded is just an app with a webview

**Comment by KikeMartinG** [comment]
MyVidster by SalsaIndy LLC

**Comment by KikeMartinG** [comment]
MyVidster by SalsaIndy LLC https://itunes.apple.com/mx/app/myvidster/id611470289?l=en&mt=8

**Comment by andrewwiik** [comment]
That app doesn't even support the X itself so I would have trouble making it support it

**Comment by andrewwiik** [comment]
Just disabled Vidster from having the other status bar, they are literally just a webview, it isn't even a real app, it wouldn't support the real X properly either
