### ISSUE TITLE
Possible to change the padding for the icons in the home screen?

### ISSUE THREAD

**Issue by mactavish14** [andrewwiik/LittleX#29]
Is it possible to bring back 6 rows for the icons. You've changed it to 5. It looks good, but I prefer 6. I know they might be slightly closer together due to the status bar, but I feel like with 5, they are too spaced out.

**Comment by KikeMartinG** [comment]
I also want this

**Comment by shehzaad10** [comment]
I would also like this, is it possible to bring back 4x6? 4x5 does not lol right on the iPhone 7 Plus. Thanks in advance
