### ISSUE TITLE
Screenshots or my guess any 16:9 picture opens up with a gap at the top.

### ISSUE THREAD

**Issue by ianrod30** [andrewwiik/LittleX#35]
[Here's a screen recording](https://streamable.com/pnbgy). It leaves a black bar at the top and pushes the bottom of the video down below the viewable screen.

**Comment by andrewwiik** [comment]
I don't understand what you are showing, like how to reproduce this video on my device

**Comment by ianrod30** [comment]
Take a screenshot on your 6 then send it to yourself, tap on the picture to see it in full screen and it opens up with the picture pushed down leaving the black bar

**Comment by andrewwiik** [comment]
Fixed in latest release
