### ISSUE TITLE
Dock and PiP not working on X

### ISSUE THREAD

**Issue by Revulate** [andrewwiik/LittleX#4]
Only tweaks installed are LittleX and InteliX. Dock won't expand and PiP shows button but doesn't work. Tried Safari and Twitch.

**Comment by andrewwiik** [comment]
Hmmmm, that doesn't make sense, I'll get my co-developer with an X to take a look into it, the PiP should def work

**Comment by Revulate** [comment]
I watched a YouTube video in Safari, and after spamming the button, I was able to read what it's trying to display.  "This video is playing in picture in picture."

**Comment by andrewwiik** [comment]
and when you press the home button it does not bring it to the home screen?

**Comment by Revulate** [comment]
I have the X. I was going to ask LQ but he's not on the Discord. But swipe up doesn't not trigger it. I've had it work with another tweak on the X.

**Comment by elsedar** [comment]
how to make it working on iphone X???
i've just pip and possibility to put 7 icons to the dock. but as i know it's not an ipad's dock at all... or it's the only features released for this moment and more to come?
