### ISSUE TITLE
App weird resolution/UI glitches on 1.6 beta.

### ISSUE THREAD

**Issue by KikeMartinG** [andrewwiik/LittleX#42]
Black bar on the right side of screen or UI glitches
![09d8deef-0769-4ed5-b95b-830e1e43c170](https://user-images.githubusercontent.com/15319495/35762446-6fa14d44-085c-11e8-987d-196375edb7d5.png)
![de217db3-ab9e-499b-9ce7-83d6f20d3d88](https://user-images.githubusercontent.com/15319495/35762447-6fc8860c-085c-11e8-835c-bfbe578e54ac.png)
![468147db-4067-4a98-8703-b27d88c774f3](https://user-images.githubusercontent.com/15319495/35762454-965d59e6-085c-11e8-8192-cd4f3f77bab5.png)
![Uploading 7842AD71-91FB-476A-8F40-B8DF95D2ED7D.png…]()

**Comment by joekempis** [comment]
yes me too :
/Users/joekempis/Downloads/IMG_0260.jpg
/Users/joekempis/Downloads/IMG_0259.jpg

**Comment by ianrod30** [comment]
Yep, I have it too on an iPhone 6s Plus. I was forced to downgrade back.

**Comment by joekempis** [comment]
yeah me too on iphone 6s plus
