### ISSUE TITLE
Bottom bar glitch

### ISSUE THREAD

**Issue by KikeMartinG** [andrewwiik/LittleX#44]
https://youtu.be/ahQTHtHp1UU

Apps this happens on:
Whatsapp
YouTube

Tweak version: 1.1.8

**Comment by andrewwiik** [comment]
Please give me a video of youtube

**Comment by KikeMartinG** [comment]
On YouTube simply the bar won’t go up, and the X bar just overlays the app. No video needed, pic shows it.
![cfec9282-b9a1-4b14-aaf6-8b753e697c6d](https://user-images.githubusercontent.com/15319495/35763616-b4c6d54c-0875-11e8-8056-0ffee2b171cc.jpeg)

**Comment by andrewwiik** [comment]
Youtube works fine for me, I'm currently trying to fix the Whatsapp bug

**Comment by KikeMartinG** [comment]
Maybe an incompatibility with the resolution as well... I’ll check later and I’ll let u know. Thanks for fixing whatsapp.

**Comment by andrewwiik** [comment]
I'm marking this issue as closed as I believe the latest version fixes these issues.
