### ISSUE TITLE
Snapchat bug on iPX

### ISSUE THREAD

**Issue by Fr0styCam** [andrewwiik/LittleX#45]
![image 2](https://user-images.githubusercontent.com/29033079/35763307-d63573b6-086e-11e8-9070-69d19d3e42c5.png)
The floating dock and PIP work great on my iPhone X but Snapchat has an issue where the top bar is much bigger than they're supposed to be, which is annoying. I haven't seen any issues in any other app though. I'm on iOS 11.1.2 and LittleX 1.1.8.
![image 1](https://user-images.githubusercontent.com/29033079/35763305-d0275caa-086e-11e8-8137-95bc6ff85671.png)

**Comment by KikeMartinG** [comment]
This is not happening to me at all. As well on 1.1.8 iOS 11.1.2
![89c6cd60-96c3-43a4-a55f-915f037eef8b](https://user-images.githubusercontent.com/15319495/35763375-aedf238c-0870-11e8-827d-64bdcab3dcc6.png)

**Comment by andrewwiik** [comment]
Fixed in 2.0.1, please update
