### ISSUE TITLE
Whatsapp call UI is pushed down and can’t see or use end call button.

### ISSUE THREAD

**Issue by maximill5000** [andrewwiik/LittleX#50]

**Comment by maximill5000** [comment]
The UI is pushed down and can’t see or use end call button.

**Comment by andrewwiik** [comment]
I will be looking into this issue tomorrow when my friend from spain can call me so I can see the UI Problem

**Comment by maximill5000** [comment]
It actually got fixed in 1.3 update

**Comment by andrewwiik** [comment]
Awesome
