### ISSUE TITLE
Status bar renders weird in Safari app during splash screen.

### ISSUE THREAD

**Issue by willrj93** [andrewwiik/LittleX#58]
Title’s pretty much it. The time and signal indicators overlap the address bar a little bit during the splash screen but once the app opens completely it re-adjusts the app accordingly. Not really a huge issue but definitely bugs my OCD a little every time I open the safari app. Can provide a picture if necessary.

i7+, iOS 11.1.2, Electra b10; issue has been present since first build

**Comment by andrewwiik** [comment]
Can't be fixed, It's a static Launch Image, using the X's image wouldn't work
