### ISSUE TITLE
Automatically disables after InteliX is installed

### ISSUE THREAD

**Issue by duraidabdul** [andrewwiik/LittleX#6]
When InteliX is installed, LittleX automatically stops working, and when InteliX is uninstalled, it begins to work again.

**Comment by andrewwiik** [comment]
hmmm Interesting

**Comment by Revulate** [comment]
This fixed my issue uninstalling InteliX. #4

**Comment by hitesh1khandelwal** [comment]
Same here.

**Comment by Revulate** [comment]
New update fixed issue. #4
