### ISSUE TITLE
HomeBar not Dissapearing

### ISSUE THREAD

**Issue by dallasgroot** [andrewwiik/LittleX#63]
Hey, with the new update it braught the option to disable certain aspects of the tweaks features, though I’ve found the Homebar doesn’t hide when that option is enabled.

**Comment by dallasgroot** [comment]
![04d65276-750f-4e45-b1f0-24cd0f15d900](https://user-images.githubusercontent.com/7484579/35774663-f5b36416-092a-11e8-825e-2c3c14c48565.png)
![576626cd-8997-4a87-8e6b-9db97ce7fbaf](https://user-images.githubusercontent.com/7484579/35774669-0113ca26-092b-11e8-8324-827acebe3c2f.png)

**Comment by andrewwiik** [comment]
Did you make sure resprang?

**Comment by dallasgroot** [comment]
Yes I did, with the built in button,  as well as killall backboardd

**Comment by andrewwiik** [comment]
Found the issue I think, working on a fix, see this is what happens when people use github

**Comment by dallasgroot** [comment]
Glad to help!

**Comment by dallasgroot** [comment]
It appears swipe up to kill app doesn’t work either

**Comment by andrewwiik** [comment]
then revert to using the other option, it doesn't work on al ldevices for some reason#meh

**Comment by andrewwiik** [comment]
Fixed, CLosing, please update

**Comment by dallasgroot** [comment]
Yes, new update fixes this bug, thanks
