### ISSUE TITLE
Weird little glitch in Safari when home bar is turned off

### ISSUE THREAD

**Issue by mactavish14** [andrewwiik/LittleX#67]
Force close safari, then open the app, and look what happens at the bottom of the app. Once the page loads, it gets pushed up slightly. A very small thing but it's annoying.

**Comment by andrewwiik** [comment]
Can't be fixed, it's a static launch image

**Comment by mactavish14** [comment]
Don’t mean to keep mentioning fluidity, but this issue is not present with that. So makes me think it can be fixed?
