### ISSUE TITLE
Problem with Uber App

### ISSUE THREAD

**Issue by shreymalhotra** [andrewwiik/LittleX#77]
The bottom half of the uber app is hidden and does not show - specifically the part that is used to request a ride. Also the search bar clashes with the status bar. screenshots attached
![img_2018](https://user-images.githubusercontent.com/21250640/35781326-7c5ccd78-099d-11e8-9d32-d630af065f34.jpg)
![img_2015](https://user-images.githubusercontent.com/21250640/35781327-7c73ddba-099d-11e8-9353-914a2da63035.jpg)

**Comment by andrewwiik** [comment]
Disable the tweak in the uber app in the settings
